#!/usr/bin/env python3
"""Phase 2 - how often do these problems actually occur?

The corpus in `evals/samples/` is generated by `generate.py` from the checks
that score it, so a perfect F1 there means the checks agree with themselves. It
cannot tell you whether any of this matters. This script answers a different
question: out of real newsletters nobody wrote for us, how many would we stop?

## The methodology caveat, stated first because it decides what the number means

A Substack or Beehiiv *archive page* is a responsive web page. Its CSS is built
by a React app and has almost nothing to do with the MIME part that landed in
anyone's inbox. Auditing one and reporting "61% fail WCAG AA" would be a
confident, meaningless number - the same fabrication this tool refuses to commit
for spam scores (D8).

So sources are ranked, and every result carries the rank it came from:

* ``sent_email``  - the real thing. A saved `.html`/`.eml` from an inbox, a Wren
  or Mailchimp export, or a "View this email in your browser" page that serves
  the sent HTML. **Only these support a claim about email.**
* ``web_archive`` - an archive/permalink page. Measures a web page. Reported on
  its own line, never blended into the headline.

`--allow-web-archive` is required before this script will fetch anything in the
second category, and the report labels it in both the table and the prose.

## Usage

    # audit whatever is already in evals/real/ (no network)
    python scripts/run_prevalence_study.py

    # add sources listed one URL per line, and audit
    python scripts/run_prevalence_study.py --fetch sources.txt

Drop exported emails straight into `evals/real/` and re-run; anything already
there is audited with no network at all.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from collections import Counter
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from preflight.audit import audit_html  # noqa: E402
from preflight.models import Severity  # noqa: E402

REAL_DIR = ROOT / "src" / "preflight" / "evals" / "real"
REPORT_PATH = ROOT / "src" / "preflight" / "evals" / "PREVALENCE_REPORT.md"
MANIFEST = REAL_DIR / "manifest.json"

#: Codes the report leads with, in the order a creator would care.
HEADLINE = [
    ("contrast.aa_fail", "Text below WCAG AA contrast"),
    ("darkmode.no_bg_override", "Collapses in forced dark mode"),
    ("img.missing_alt", "Image with no alt text"),
    ("link.broken", "Dead or 404 link"),
    ("liquid.unparsed", "Unclosed Liquid tag"),
    ("deliverability.image_heavy", "Image-heavy with thin copy"),
]

#: A "view in browser" URL usually serves the sent HTML; an archive path does not.
SENT_EMAIL_HINTS = ("/view-in-browser", "view_in_browser", "/vb/", "campaign-archive",
                    "us[0-9]*.campaign-archive.com", "/email/")


def classify(url: str) -> str:
    lowered = url.lower()
    if any(h.strip("[0-9]*") in lowered for h in SENT_EMAIL_HINTS):
        return "sent_email"
    return "web_archive"


def load_manifest() -> dict:
    if MANIFEST.exists():
        return json.loads(MANIFEST.read_text())
    return {}


def save_manifest(data: dict) -> None:
    MANIFEST.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def fetch(urls: list[str], allow_web_archive: bool) -> dict:
    """Save each URL's raw HTML into evals/real/, recording its provenance.

    Raw bytes, not a markdown rendition: contrast, dark mode and alt text all
    live in the CSS and attributes, and a converted page has none of them.
    """
    import urllib.request

    manifest = load_manifest()
    REAL_DIR.mkdir(parents=True, exist_ok=True)
    for url in urls:
        source = classify(url)
        if source == "web_archive" and not allow_web_archive:
            print(f"  skip (web archive, needs --allow-web-archive): {url}")
            continue
        name = "".join(c if c.isalnum() or c in "-_" else "-" for c in url)[-80:] + ".html"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "preflight-prevalence/0.1"})
            with urllib.request.urlopen(req, timeout=20) as resp:
                html = resp.read().decode("utf-8", errors="replace")
        except Exception as exc:                      # noqa: BLE001 - report and continue
            print(f"  failed: {url} ({exc.__class__.__name__})")
            continue
        (REAL_DIR / name).write_text(html)
        manifest[name] = {"url": url, "source": source, "fetched": date.today().isoformat()}
        print(f"  saved [{source}] {name}")
    save_manifest(manifest)
    return manifest


async def audit_corpus(check_links: bool) -> list[dict]:
    manifest = load_manifest()
    rows: list[dict] = []
    files = sorted(p for p in REAL_DIR.glob("*.html"))
    for path in files:
        html = path.read_text()
        report = await audit_html(
            html, path=path.name,
            offline_links=None if check_links else {},
            skip_llm=True,          # Module A only: the reviewer costs money and
        )                           # adds no prevalence signal.
        meta = manifest.get(path.name, {})
        rows.append({
            "file": path.name,
            "source": meta.get("source", "sent_email" if not meta else "web_archive"),
            "url": meta.get("url", ""),
            "verdict": report.verdict,
            "codes": sorted({f.code for f in report.findings}),
            "blocking": len(report.blocking_findings),
            "words": report.stats.get("words", 0),
        })
    return rows


def summarize(rows: list[dict]) -> dict:
    """Share of *documents* carrying each code - never share of findings.

    One newsletter with forty contrast failures is one newsletter with a
    contrast problem. Counting findings would let a single pathological
    document set the headline.
    """
    n = len(rows)
    if not n:
        return {"documents": 0, "codes": {}, "verdicts": {}}
    docs_with: Counter = Counter()
    for row in rows:
        for code in row["codes"]:
            docs_with[code] += 1
    return {
        "documents": n,
        "codes": {c: {"documents": k, "share": k / n} for c, k in docs_with.most_common()},
        "verdicts": {v: k / n for v, k in Counter(r["verdict"] for r in rows).most_common()},
        "hold_share": sum(1 for r in rows if r["verdict"] == "HOLD") / n,
    }


def render(rows: list[dict]) -> str:
    sent = [r for r in rows if r["source"] == "sent_email"]
    web = [r for r in rows if r["source"] == "web_archive"]
    s_sent, s_web, s_all = summarize(sent), summarize(web), summarize(rows)

    def table(summary: dict) -> str:
        if not summary["documents"]:
            return "_No documents in this category yet._\n"
        out = ["| Problem | Newsletters affected | Share |", "| --- | ---: | ---: |"]
        for code, label in HEADLINE:
            row = summary["codes"].get(code, {"documents": 0, "share": 0.0})
            out.append(f"| {label} | {row['documents']} / {summary['documents']} "
                       f"| {row['share'] * 100:.0f}% |")
        return "\n".join(out) + "\n"

    lines = [
        "# Prevalence study",
        "",
        f"_Generated {date.today().isoformat()} by `scripts/run_prevalence_study.py`._",
        "",
        "How often do the problems this tool checks for actually occur in "
        "newsletters nobody wrote for us? The synthetic corpus in `../samples/` "
        "cannot answer that - it is generated from the checks that score it.",
        "",
        "## Sample",
        "",
        f"- **{len(sent)}** sent-email sources (exports, saved inbox HTML, "
        "view-in-browser pages that serve the sent HTML)",
        f"- **{len(web)}** web-archive pages",
        "",
    ]

    if not rows:
        lines += [
            "## No corpus yet",
            "",
            "`evals/real/` is empty, so there is nothing to report and this file "
            "states that rather than inventing a number.",
            "",
            "Add real broadcast HTML to `src/preflight/evals/real/` and re-run. "
            "See that directory's README for what qualifies and how to strip "
            "subscriber data first.",
            "",
        ]
        return "\n".join(lines)

    lines += ["## Sent email", "",
              "**These are the only rows that support a claim about email.**", "",
              table(s_sent), ""]
    if sent:
        lines += [f"**{s_sent['hold_share'] * 100:.0f}%** of sent emails sampled "
                  f"would be held before sending.", ""]

    if web:
        lines += [
            "## Web archive pages", "",
            "> **Read this before quoting the numbers below.** These are archive "
            "pages, not sent email. Their CSS is generated by the publisher's web "
            "app and has little to do with the MIME part that reached an inbox. "
            "They are reported for completeness and are deliberately **not** "
            "blended into the headline.",
            "",
            table(s_web), "",
        ]

    lines += ["## Every code observed", "",
              "| Code | Documents | Share |", "| --- | ---: | ---: |"]
    for code, row in s_all["codes"].items():
        lines.append(f"| `{code}` | {row['documents']} / {s_all['documents']} "
                     f"| {row['share'] * 100:.0f}% |")
    lines += ["", "## Method", "",
              "- Module A only. The intent reviewer costs money per document and "
              "adds no prevalence signal.",
              "- Share is the fraction of **documents** carrying a code at least "
              "once, never the fraction of findings.",
              "- Link probing is live unless `--no-link-check` was passed, so "
              "`link.broken` reflects the web on the generation date above.",
              "- Raw sources and their provenance are in `real/manifest.json`.",
              ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fetch", metavar="FILE",
                    help="Text file of source URLs, one per line.")
    ap.add_argument("--allow-web-archive", action="store_true",
                    help="Permit fetching archive pages, which measure web pages, not email.")
    ap.add_argument("--no-link-check", action="store_true",
                    help="Skip live link probing.")
    ap.add_argument("--json", action="store_true", help="Print rows as JSON.")
    args = ap.parse_args()

    if args.fetch:
        urls = [ln.strip() for ln in Path(args.fetch).read_text().splitlines()
                if ln.strip() and not ln.startswith("#")]
        print(f"Fetching {len(urls)} sources into {REAL_DIR}/")
        fetch(urls, allow_web_archive=args.allow_web_archive)

    rows = asyncio.run(audit_corpus(check_links=not args.no_link_check))
    if args.json:
        print(json.dumps({"rows": rows, "summary": summarize(rows)}, indent=2))
        return 0

    REPORT_PATH.write_text(render(rows))
    print(f"Audited {len(rows)} documents → {REPORT_PATH.relative_to(ROOT)}")
    if not rows:
        print("  evals/real/ is empty. The report says so rather than "
              "inventing a distribution.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
